name: Full Test

on:
    push:
    workflow_dispatch:
    pull_request:
        types: [assigned, opened, synchronize, reopened]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
                django-version: ['<3.2', '<3.3', '<4.2', '<4.3', '<5.1']
                exclude:
                    - python-version: '3.7'
                      django-version: '<5.1'
                    - python-version: '3.8'
                      django-version: '<5.1'
                    - python-version: '3.9'
                      django-version: '<5.1'
                    - python-version: '3.12'
                      django-version: '<3.2'
                    - python-version: '3.12'
                      django-version: '<3.3'

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install core
              run: pip install --pre "Django${{ matrix.django-version }}" "pydantic<3"
            - name: Install tests
              run: pip install pytest pytest-asyncio pytest-django psycopg2-binary
            - name: Test
              run: pytest .
